### ISSUE TITLE
CRAN snapshot startup message not accurate if changed in .Rprofile

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/RRO#161] opened 2015-06-02 22:22 UTC
User reports: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/rropen/aSnf4vJf6aM/V-E3U3GmrOMJ

```
I've just installed Revolution R Open 3.2.0 on Windows 7 (64 bit).

Currently I prefer to use the most recent CRAN updates.  I've created an .Rprofile file in my home directory that contains:

options(repos = c(CRAN = "http://cran.revolutionanalytics.com"))

However, when I start RRO, I continue to get the message at startup:

"Using CRAN snapshot taken on 2015-05-01"
```

Make the CRAN snapshot message in .Rprofile.site check for the use of an MRAN snapshot programatically and report a message like:

```
"Using CRAN snapshot taken on %DATE%"
```

If the CRAN mirror is not an MRAN snapshot, print:

```
"Using CRAN mirror: %URL%"
```

**Comment by j-martens** [comment] 2015-06-02 22:26
duplicate of #158

**Closed by j-martens** 2015-06-02 22:26 UTC
Labels: Bug - minor
