### ISSUE TITLE
Ubuntu deb package doesn't include repositories file

### ISSUE THREAD

**Issue by grumpycatt** [RevolutionAnalytics/RRO#124] opened 2015-04-13 12:15 UTC
As I'm testing RRO latest version on Ubuntu, I found out that the repositories file isn't included into the .deb package RRO-8.0.2-Beta-Ubuntu-14.04.x86_64.deb, which is causing some errors during packages installation (i.e. bioconductor)

A thread was already opened regarding to that issue,
https://groups.google.com/forum/#!topic/rropen/sJRJE9khzuw

I need to put this, https://github.com/RevolutionAnalytics/RRO/blob/master/R-src/etc/repositories, into /usr/lib64/RRO-8.0.2/R-3.1.2/lib/R/etc/ and eventually to add this in the .deb package also.

Kind regards,

**Comment by revodavid** [comment] 2015-04-13 13:35
Thanks for the report. This is a duplicate of #94 , so I'll close this issue, which is targeted to be fixed in 8.0.3.

**Closed by revodavid** 2015-04-13 13:35 UTC
