### ISSUE TITLE
Error loading Matrix library

### ISSUE THREAD

**Issue by bhaskarvk** [RevolutionAnalytics/RRO#98] opened 2015-02-18 18:29 UTC
OS - OS X Yosemite
Revo version - 
```
 sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

> Revo.version
      _        
major 8        
minor 0.1-beta2

```

```
> library(Matrix)
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Matrix/libs/Matrix.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Matrix/libs/Matrix.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.1/Resources/lib/libRlapack.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.1/Resources/library/Matrix/libs/Matrix.so
  Reason: image not found
Error: package or namespace load failed for ‘Matrix’
```

I'm not on snapshot repository, My repository is 'http://cran.revolutionanalytics.com' coz I need quite a few latest updates.

**Comment by revodavid** [comment] 2015-02-18 19:11
Thanks for letting us know about this issue, which will be fixed in the next update. In the meantime, you can find a workaround here: https://github.com/RevolutionAnalytics/RRO/releases/tag/v8.0.1-beta2

**Comment by revodavid** [comment] 2015-02-18 19:12
Closing: Duplicate of #88

**Closed by revodavid** 2015-02-18 19:12 UTC
